#!/usr/bin/env bash
. ./scripts/env.sh
echo
echo "RUNNING TESTS"
echo

if [[ -n $CIRCLE_ARTIFACTS ]]; then
    dir=$CIRCLE_ARTIFACTS/v$NODE_VERSION
else
    dir=./coverage/v$NODE_VERSION
fi

istanbul=$(npm run which --loglevel silent -- istanbul)
mocha=$(npm run which --loglevel silent -- _mocha)

$istanbul cover $mocha 'lib/**/*.spec.js' --dir $dir/coverage
