#!/usr/bin/env bash
. ./scripts/env.sh
echo
echo "RUNNING INSTRUMENTATION TESTS"
echo

if [[ -z $INSTR_TARGET_VERSIONS ]]; then
    INSTR_TARGET_VERSIONS=one
fi

cd ./test/instrumentations
make test TARGET_VERSIONS=$INSTR_TARGET_VERSIONS \
    NODE_INDEX=$NODE_INDEX NODE_TOTAL=$NODE_TOTAL
